### ISSUE TITLE
Pretrained weights and demo available?

### ISSUE THREAD

**Issue by txytju** [DUT-CSJ/PVUW2023-VSS-3rd#1]

**Comment by DUT-CSJ** [comment]
Thank you for your attention,
the final model weight has been uploaded to https://drive.google.com/file/d/18slzp3azV_XHrXCTu3KAQW7mKW62-kEk/view?usp=drive_link. 
We do not have a plan to create a demo, you can use the provided weight for inference. 
We will organize the inference commands and provide them later.

Additionally, may I ask if you are also a participant in the VSS track?
best,
Chang
