### ISSUE TITLE
pretrained model

### ISSUE THREAD

**Issue by chenjun2hao** [DUT-CSJ/PVUW2023-VSS-3rd#3]
Please agree the email to download the pre-training model. thanks!!

**Comment by DUT-CSJ** [comment]
> Please agree the email to download the pre-training model. thanks!!

I have shared the pre-trained weight, please check it.
Feel free to ask me if you have any question!

**Comment by chenjun2hao** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
